site_name: 2024.2 - ARANDU

repo_name: "2024.2 - ARANDU"
repo_url: "https://github.com/fga-eps-mds/2024.2-CALCULUS-DOC"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: black
      background: black
      text: white
      code: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: black
      background: black
      text: white
      code: white
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Poppins
    code: Inconsolata
  font_size:
    text: 16px
    code: 14px
  locale: pt_BR

user_color_mode_toggle: true

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: "index.md"
  - Guias:
      - Guia de Contribuição: "guias/guia_de_contribuicao.md"
  - Equipe:
      - Planejamento de Comunicação: "equipe/planejamento_de_comunicacao.md"
      - Gestão de Conhecimentos: "equipe/gestao_de_conhecimentos.md"
      - Gestão de Pareamentos: "equipe/gestao_de_pareamento.md"
  - Atas:
      - Ata dia 22/10/2024: "Atas/ata_reuniao_22_10_24.md"
      - Ata dia 23/10/2024: "Atas/ata_reuniao_23_10_24.md"
      - Ata dia 29/10/2024: "Atas/ata_reuniao_29_10_24.md"
      - Ata dia 30/10/2024: "Atas/ata_reuniao_30_10_24.md"
      - Ata dia 02/11/2024: "Atas/ata_reuniao_02_11_24.md"
      - Ata dia 04/11/2024: "Atas/ata_reuniao_04_11_24.md"
      - Ata dia 05/11/2024: "Atas/ata_reuniao_05_11_24.md"
      - Ata dia 06/11/2024: "Atas/ata_reuniao_06_11_24.md"
      - Ata dia 07/11/2024: "Atas/ata_reuniao_07_11_24.md"
      - Ata dia 09/11/2024: "Atas/ata_reuniao_09_11_24.md"
      - Ata dia 20/11/2024: "Atas/ata_reuniao_20_11_24.md"
      - Ata dia 23/11/2024: "Atas/ata_reuniao_23_11_24.md"
  
  - Lean Inception:
    - Visão do Produto: 'Lean_Inception/Vis_prod.md'
    - É - Não É - Faz - Não Faz: 'Lean_Inception/E_nao_e.md'
    - Objetivos do Produto: 'Lean_Inception/obj_prod.md'
    - Personas: 'Lean_Inception/personas.md'
    - Jornada: 'Lean_Inception/jornada.md'
    - Brainstorm: 'Lean_Inception/brainstorm.md'
    - Revisão Técnica, de Negócio e de UX: 'Lean_Inception/rev_tec.md'
    - Sequenciador: 'Lean_Inception/sequencia.md'
    - Canvas MVP: 'Lean_Inception/canvas_mvp.md'
  - Estrutura Analítica do Projeto: 'projeto/estrutura_analitica.md'
  - Documento de Arquitetura: 'projeto/arquitetura.md'
  # - Documentação Técnica:
  #   - Termo de Abertura do Projeto: 'organizacoes/tap.md'
  #   - Documento de Arquitetura: 'organizacoes/documento_arquitetura.md'
  #   - Estrutura Analítica do Projeto: 'organizacoes/eap.md'
  #   - Visão de Dados: 'organizacoes/visao-de-dados.md'
  #   - Visão de Endpoints: 'organizacoes/visao-de-endpoints.md'
  #   - Manual de Instruções: 'organizacoes/manual_de_instruções.md'
  # - Gestão do Projeto:
  #   - Plano de Comunicação: 'planejamento/plano_comunicacao.md'
  #   - Plano de Qualidade: 'planos/plano_qualidade.md'
  #   - Plano de Custos: 'planos/planos_custos.md'
  #   - EVM: 'organizacoes/EVM.md'
  #   - Analise de Riscos: 'planos/planos_riscos.md'
  #   - Quadro de Conhecimento e Pareamento: 'planejamento/conhecimento_pareamento.md'
  # - Guias:
  #   - Guia de Contribuição: 'guias/guia-contribuicao.md'
  #   - Guia de Estilo: 'guias/guia-estilo.md'
  #   - Código de Conduta: 'guias/codigo-conduta.md'
  # - Dojos:
  #   - Dojo Markdown: 'dojo/dojo-markdown.md'
  #   - Dojo Git: 'dojo/dojo-git.md'
  #   - Dojo Docker: 'dojo/dojo-docker.md'
  #   - Dojo Frontend: 'dojo/dojo-frontend.md'
  # - Encerramento:
  #   - Post Mortem: 'encerramento/post-mortem.md'
